/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ktmonkey

import ktmonkey.repl.Repl

fun main() {
    val username = System.getProperty("user.name")
    println("Hello $username! This is the Monkey programming language!")
    println("Feel free to type in commands")
    Repl.start()
}
